# Generated by Django 3.2.6 on 2021-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
