# Generated by Django 3.2.6 on 2021-08-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_instauser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(default='media/prof_pic/prof_m.png', upload_to=''),
        ),
    ]
