# Generated by Django 3.2.6 on 2021-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_instauser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
