# Generated by Django 3.2.6 on 2021-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_alter_instauser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
