# Generated by Django 3.2.6 on 2021-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_instauser_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
