# Generated by Django 3.2.6 on 2021-08-26 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_auto_20210826_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
