# Generated by Django 3.2.6 on 2021-08-26 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='InstaUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
