# Generated by Django 3.2.6 on 2021-08-29 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0024_alter_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 29, 13, 12, 34, 927924)),
        ),
    ]
