# Generated by Django 3.2.6 on 2021-08-30 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0026_auto_20210830_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='app_users.instauser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 30, 11, 32, 29, 771536)),
        ),
    ]
