# Generated by Django 3.2.6 on 2021-09-04 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0028_auto_20210830_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 4, 13, 31, 40, 796489)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 4, 13, 31, 40, 796975)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
