# Generated by Django 3.2.6 on 2021-09-04 08:41

import app_users.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0029_auto_20210904_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 4, 13, 41, 18, 218372)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='gen_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 4, 13, 41, 18, 218936)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.FileField(upload_to='posts/', validators=[app_users.validators.file_size]),
        ),
    ]
